# Archivo: csds60_en.py
# Autor: Jorge Aguirre Andreu
# Descripción: Archivo de idioma ingles. 
#
#   Copyright (C) 2009  Jorge Aguirre Andreu
#
#   This file is part of CSDs60.
#   CSDs60 is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   CSDs60 is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

csds60={
    u"SALIR":u"Exit",
    u"SÍ":u"Yes",
    u"NO":u"No",
    u"HASTA LUEGO":u"See you later",
    u"¿ESTÁ SEGURO?":u"Are you sure?",
    u"MENUDIARIO":u"        Diary",
    u"MENUDIETA":u" Calculate Dosis",
    u"MENUCONFIGURACIÓN":u"  Preferences",
    u"MENUEXPORTAR":u"      Export",
    u"MENUCITASMÉDICAS":u"Medical dates",
    u"MENUESTADÍSTICAS":u"    Stadistics",
    u"ENERO":u"January",
    u"FEBRERO":u"February",
    u"MARZO":u"March",
    u"ABRIL":u"April",
    u"MAYO":u"May",
    u"JUNIO":u"June",
    u"JULIO":u"July",
    u"AGOSTO":u"August",
    u"SEPTIEMBRE":u"September",
    u"OCTUBRE":u"October",
    u"NOVIEMBRE":u"November",
    u"DICIEMBRE":u"December",
    u"DIAS":u"M      T      W      T       F       S       S",
    u"DIARIO":u"Diary",
    u"VOLVER":u"Back",
    u"OPCIONES":u"Options",
    u"ANTES":u"Before",
    u"DESPUES":u"After",
    u"DESAYUNO":u"Breakfast",
    u"MEDIAMAÑANA":u"Midmorning",
    u"DOSIS":u"Dosis",
    u"DEPORTE":u"Sport",
    u"ALMUERZO":u"Lunch",
    u"MERIENDA":u"Tea hour",
    u"CENA":u"Dinner",
    u"RESOPON":u"Midnight",
    u"ORINA":u"Orine",
    u"ACETONA":u"Acetone",
    u"GLUCAGON":u"Glucagon",
    u"EXTRA":u"Extra",
    u"DIETA":u"Calculate Dosis",
    u"CONFIGURACION":u"  Preferences",
    u"CITAS":u"Medical Dates",
    u"EXPORTAR":u"  Export",
    u"NOTAS ADICIONALES":u"Extra notes",
    u"MEDICAMENTOS":u"Medicines",
    u"ESCRIBE TEXTO:":u"Type text:",
    u"COMIDAS":u"Meals",
    u"LIC":u"License",
    u"T":u"This program comes with",
    u"T1":u"ABSOLUTELY NO WARRANTY;",
    u"T2":u"This is free software,",
    u"T3":u"and you are welcome to redistribute it",
    u"T4":u"under certain conditions. See",
    u"NADA":u"Nothing",
    u"EST":u"  Stadistics",
    u"XML":u"Data to XML",
    u"HTML":u"Data to HTML",
    u"BLUET":u"Send data on Bluetooth",
    u"XML GEN":u"XML Created",
    u"HTML GEN":u"HTML Created",
    u'XML CARGA':u"Load the XML, press OK:",
    u'HTML CARGA':u"Load the HTML, press OK:",
    u"ARCH ENVIADOS":u"Sent Files",
    u"NUEVO":u"new",
    u"CITA":u"Dates",
    u"NREG":u"New record",
    u"BREG":u"Records deleted",
    u"IDIOMA":u"Language selection",
    u"PERSONAL":u"Personal settings",
    u"BD":u"Database selection",
    u"ALARMA":u"Alarm settings",
    u"SIDIOMA":u"Select a language",
    u"REINICIA":u"You have to reboot the Python",
    u"REINICIA1":u"shell for the new settings",
    u"INSU":u"Insert insuline",
    u"SBD":u"Select a data base",
    u"VERCITAS":u"Show Dates",
    u"PESO":u"Weight",
    u"ALTURA":u"Height",
    u"TOTALINSU":u"Total insuline quantity",
    u"RATD":u"Breakfast ratio",
    u"RATA":u"Lunch ratio",
    u"RATC":u"Dinner ratio",
    u"ADDINSULINA":u"Add new insuline",
    u"ELIMINSULINA":u"View availables insulines",
    u"BORRAINSU":u"You have to push the keyboard",
    u"BORRAINSU1":u"select button for remove",
    u"BORRAINSU2":u"the selected insuline",
    u"RESETINSU":u"Reset insuline values",
    u"ALARMATIRAS":u"Tiras for alarm",
    u"QTIRASACT":u"Current amount of tiras",
    u"QTIRASTOTAL":u"Full amount of tiras",
    u"RESETTIRAS":u"Reset amount of tiras",
    u"QTIRASRESTA":u"Tiras for rest",
    u"TEQUEDAN":u"You have got ",
    u"GLUCACTUAL":u"Current glucose",
    u"TIPO1":u"Lacteous",
    u"TIPO2":u"Farinaceous/Paste",
    u"TIPO3":u"Legumbres/Patatas",
    u"TIPO4":u"Fruits",
    u"TIPO5":u"Vegetables",
    u"TIPO6":u"Fish/Meat",
    u"CALCINSU":u"Dosis quantity APROXIMATION",
    u"CALCULODOSIS":u"Calculate",
    u"VASO":u"glass/es",
    u"PIEZA":u"piece/s",
    u"PLATO":u"plate/s"
    }