# Archivo: csds60_es.py
# Autor: Jorge Aguirre Andreu
# Descripción: Archivo de idioma español. 
#
#   Copyright (C) 2009  Jorge Aguirre Andreu
#
#   This file is part of CSDs60.
#   CSDs60 is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   CSDs60 is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

csds60={
    u"SALIR":u"Salir",
    u"SÍ":u"Sí",
    u"NO":u"No",
    u"HASTA LUEGO":u"Hasta luego",
    u"¿ESTÁ SEGURO?":u"¿Está seguro?",
    u"MENUDIARIO":u"       Diario",
    u"MENUDIETA":u"Calcular Dosis",
    u"MENUCONFIGURACIÓN":u"Configuración",
    u"MENUEXPORTAR":u"    Exportar",
    u"MENUCITASMÉDICAS":u"Citas médicas",
    u"MENUESTADÍSTICAS":u"  Estadísticas",
    u"ENERO":u"Enero",
    u"FEBRERO":u"Febrero",
    u"MARZO":u"Marzo",
    u"ABRIL":u"Abril",
    u"MAYO":u"Mayo",
    u"JUNIO":u"Junio",
    u"JULIO":u"Julio",
    u"AGOSTO":u"Agosto",
    u"SEPTIEMBRE":u"Septiembre",
    u"OCTUBRE":u"Octubre",
    u"NOVIEMBRE":u"Noviembre",
    u"DICIEMBRE":u"Diciembre",
    u"DIAS":u"L      M       X       J       V       S       D",
    u"DIARIO":u"Diario",
    u"VOLVER":u"Volver",
    u"OPCIONES":u"Opciones",
    u"ANTES":u"Antes",
    u"DESPUES":u"Después",
    u"DESAYUNO":u"Desayuno",
    u"MEDIAMAÑANA":u"Mediamañana",
    u"DOSIS":u"Dosis",
    u"DEPORTE":u"Deporte",
    u"ALMUERZO":u"Almuerzo",
    u"MERIENDA":u"Merienda",
    u"CENA":u"Cena",
    u"RESOPON":u"Resopón",
    u"ORINA":u"Orina",
    u"ACETONA":u"Acetona",
    u"GLUCAGON":u"Glucagón",
    u"EXTRA":u"Extra",
    u"DIETA":u"Calcular Dosis",
    u"CONFIGURACION":u"Configuración",
    u"CITAS":u"Citas Médicas",
    u"EXPORTAR":u"Exportar",
    u"NOTAS ADICIONALES":u"Notas extra",
    u"MEDICAMENTOS":u"Medicamentos",
    u"ESCRIBE TEXTO:":u"Escribe texto:",
    u"COMIDAS":u"Comidas",
    u"LIC":u"Licencia",
    u"T":u"Este programa viene",
    u"T1":u"EN ABSOLUTO SIN GARANTÍA;",
    u"T2":u"Esto es free software,",
    u"T3":u"y puedes redistribuirlo sin problemas",
    u"T4":u"bajo ciertas condiciones. Más info aquí",
    u"NADA":u"Nada",
    u"EST":u"Estadísticas",
    u"XML":u"Exportar datos a XML",
    u"HTML":u"Exportar datos a HTML",
    u"BLUET":u"Enviar datos por Bluetooth",
    u"XML GEN":u"XML Generado",
    u"HTML GEN":u"HTML Generado",
    u'XML CARGA':u"Carga el XML, pulsa OK:",
    u'HTML CARGA':u"Carga el HTML, pulsa OK:",
    u"ARCH ENVIADOS":u"Archivos enviados",
    u"NUEVO":u"nuevo",
    u"CITA":u"Citas",
    u"NREG":u"Nuevo registro",
    u"BREG":u"Registros eliminados",
    u"IDIOMA":u"Selección de idioma",
    u"PERSONAL":u"Ajustes personales",
    u"BD":u"Cambiar base de datos",
    u"ALARMA":u"Ajustes de alarma",
    u"SIDIOMA":u"Seleccione un idioma",
    u"REINICIA":u"Debe reiniciar la consola",
    u"REINICIA1":u"de Python para los nuevos ajustes",
    u"INSU":u"Insertar insulinas",
    u"SBD":u"Seleccione una base de datos",
    u"VERCITAS":u"Ver Citas",
    u"PESO":u"Peso",
    u"ALTURA":u"Altura",
    u"TOTALINSU":u"Cantidad total insulina",
    u"RATD":u"Insulina desayuno",
    u"RATA":u"Insulina almuerzo",
    u"RATC":u"Insulina cena",
    u"ADDINSULINA":u"Añadir nueva insulina",
    u"ELIMINSULINA":u"Ver insulinas disponibles",
    u"BORRAINSU":u"Para borrar la insulina seleccionada,",
    u"BORRAINSU1":u"tienes que pulsar el botón",
    u"BORRAINSU2":u"select del teclado",
    u"RESETINSU":u"Valores insulina reseteados",
    u"ALARMATIRAS":u"Tiras para alarma",
    u"QTIRASACT":u"Cantidad de tiras actual",
    u"QTIRASTOTAL":u"Cantidad de tiras total",
    u"RESETTIRAS":u"Resetear cantidad tiras",
    u"QTIRASRESTA":u"Tiras a restar",
    u"TEQUEDAN":u"Te quedan ",
    u"GLUCACTUAL":u"Glucosa actual",
    u"TIPO1":u"Lácteos",
    u"TIPO2":u"Farináceos/Pasta",
    u"TIPO3":u"Legumbres/Patatas",
    u"TIPO4":u"Frutas",
    u"TIPO5":u"Verduras",
    u"TIPO6":u"Pescado/Carne",
    u"CALCINSU":u"Cálculo dosis APROXIMADA",
    u"CALCULODOSIS":u"Calcular",
    u"VASO":u"vaso/os",
    u"PIEZA":u"pieza/as",
    u"PLATO":u"plato/os",
    u"MOMENTO":u"Momento del día",
    u"HIPO":u"¡Toma algo para subir el nivel de azúcar!"
    }